### ISSUE TITLE
utxo.hdIndex -> unknown attribute?

### ISSUE THREAD

**Issue by the-phoenix** [Bitcoin-com/bch-cli-wallet#15]
I saw its using [`utxo.hdIndex`](https://github.com/Bitcoin-com/bch-cli-wallet/blob/master/src/commands/send-all.js#L138) but there's no `hdIndex` attribute in my utxo.
![image](https://user-images.githubusercontent.com/9201924/54479378-c30de100-4824-11e9-86ee-e7704710fad9.png)
Would you please clarify this?

**Comment by christroutner** [comment]
`hdIndex` is not a native property that is passed back by BITBOX. It created when the `appUtil.getUTXOs()` is called and returned by that utility function:
https://github.com/Bitcoin-com/bch-cli-wallet/blob/master/src/util.js#L94
